language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=generalizedtrees --cov-report xml

after_success:
  - bash < (curl -s https://codecov.io/bash) || echo "Codecov failed"